[package]
name = "streamedresponse"
version = "0.1.0"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.2"
tokio = { version = "0.2", features = ["macros"] }
gif = "0.10.3"
rusttype = "0.8.2"
serde = { version = "1.0.104", features = ["derive"] }
shakmaty = "0.16.2"
serde_with = "1.4.0"
