[package]
name = "lila-gif"
version = "0.1.0"
publish = false
description = "Webservice to render gifs of chess positions and games"
repository = "https://github.com/niklasf/lila-gif"
readme = "README.md"
license = "AGPL-3.0+"
authors = ["Niklas Fiekas <niklas.fiekas@backscattering.de>"]
categories = ["games", "multimedia"]
keywords = ["chess", "gif"]
edition = "2018"

[dependencies]
warp = "0.2"
tokio = { version = "0.2", features = ["macros"] }
rusttype = "0.8"
serde = { version = "1.0", features = ["derive"] }
shakmaty = "0.16"
serde_with = "1.4"
gift = { git = "https://github.com/niklasf/gift", branch = "high-bit" } # https://github.com/DougLau/gift/pull/3
ndarray = "0.13"
bytes = "0.5"
arrayvec = { version = "0.5.1", features = ["serde"] }
structopt = "0.3"
